# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

.cache:
  variables:
    CARGO_HOME: "${CI_PROJECT_DIR}/cargo_cache"
  before_script:
    - mkdir -p cargo_cache
    - echo $CARGO_HOME
    - apt-get update -qq && apt-get install -y -qq --no-install-recommends build-essential m4 llvm libclang-dev clang
    - rm -rf ../naom
    - rm -rf ../keccak-prime
    - git clone --depth=1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/zenotta/naom.git ../naom
    - git clone --depth=1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/zenotta/keccak-prime.git ../keccak-prime
  cache:
    when: 'on_success'
    key:
      files:
        - Cargo.lock
    paths:
      # Rust cache: All cargo to handle librocksdb-sys
      - cargo_cache
      - target/

# Build ZNP artifacts for a release
build:
  extends: '.cache'
  only:
    - main
    - develop
    - feature/artifacts
  stage: build
  cache:
    key:
      prefix: build
  script:
      # Print version info for debugging
    - rustc --version && cargo --version  
    - cargo build --bins --release --features=config_override
    - ls ./target/release/ -l
    - echo "BUILD_CI_JOB_ID=$CI_JOB_ID" >> build.env
  artifacts:
    reports:
      dotenv: build.env
    paths:
      - target/release/node
      - target/release/upgrade
      - src/bin/*.toml 
      - src/bin/*.json 
      - src/bin/*.sh 

deploy:
  stage: deploy
  variables:
    zenotta_env: $zenotta_env
    znp_project_id: $CI_PROJECT_ID
    znp_job_id: $BUILD_CI_JOB_ID
    znp_deploy_binaries: "true"
    apply_changes: "true"
  needs:
    - job: build
      artifacts: true
  trigger:
    project: zenotta/devops
    branch: develop
    strategy: depend
  rules:
    - if: $deploy_binaries == "true" 

# Test and lint the project: do not build binaries
# that require rocksdb and other dependencies
test:cargo:
  extends: '.cache'
  only:
    - merge_requests
  cache:
    key:
      prefix: test2
  script:
    - rustc --version && cargo --version  
      # Print version info for debugging
    - cargo test --workspace --verbose --features=config_override

lint:rustfmt:
  only:
    - merge_requests
  script:
    - rustup component add rustfmt
    - rustc --version && cargo --version  
      # Print version info for debugging
    - cargo fmt -- --check

lint:clippy:
  extends: '.cache'
  only:
    - merge_requests
  cache:
    key:
      prefix: clippy
  script:
    - rustup component add clippy
    - rustc --version && cargo --version  
      # Print version info for debugging
    - cargo clippy --all-targets -- -D warnings
